### ISSUE TITLE
Error using text

### ISSUE THREAD

**Issue by grundm** [zelanolab/breathmetrics#1]
Thank you for the amazing toolbox and the great documentation. Currently, I am working through the demo but I get the following error

Error using text
First two or three arguments must be numeric doubles.

Error in demo (line 270)
    text(bm.time(bm.inhalePeaks(i)),bm.peakInspiratoryFlows(i), ...

https://github.com/zelanolab/breathmetrics/blob/fbe4e6f5cd016c5c641bfd0a30fde628e0e56b10/demo.m#L270

**Comment by torbenator** [comment]
Hi. Thanks for trying this out and I'd be happy to help you!

I'm trying to figure out where this error is coming from but I'm having some trouble. I just ran that line of the demo again on my machine but I don't get that error for some reason. 

bm.time(i) and bm.peakInspiratoryFlows(i) should definitely be numeric doubles. What values are bm.inhalePeaks(i) and bm.peakInspiratoryFlows(i)? If you are using the sample data they should be 3.4 and 1.8, respectively. 

Can you confirm that you ran the code in the cells above to estimate the peaks?
(simply running:  bm.estimateAllRespiratoryFeatures();  should be sufficient.)

The simulation code can output buggy respiratory traces with extreme inputs. Is that maybe the case?

What version of Matlab are you using? I designed this for 2017A and I haven't updated it for the newer versions and that may very well be causing your problem.

Sorry about the bug and I'll think more about what could have caused it as I wait for your response.
Thanks again!

**Comment by grundm** [comment]
bm.time -> double
bm.peakInspiratoryFlows -> single
bm.inhalePeaks -> double

I used my own data recorded with Brain Products' respiration belt (https://www.brainproducts.com/productdetails.php?id=49&tab=1) and loaded the data with EEGLAB. My original data is single. Your "sample_data.mat" is double. So I converted mine and it worked. I used Matlab 9.3.0 (R2017b).
