### ISSUE TITLE
Using the GUI with 'humanBB' data type

### ISSUE THREAD

**Issue by marcpabst** [zelanolab/breathmetrics#3]
Hi there,

Thanks for the recent update - it looks great!

But I'm wondering if it's possible to use breast belt data with the newly introduced gui feature? When I set the data type to "humanBB", I can see individual breaths listed in the gui but get no plotting at all. However, using "humanAirflow" I get breaths plotted and can interact with them as intended.

Code:
```matlab
dataType = 'humanBB';

bmObj = breathmetrics(respiratoryTrace, srate, dataType);
bmObj.estimateAllFeatures();

cleanedBmObj=bmGui(bmObj);
```

Output (using "humanBB)":
```
Index exceeds the number of array elements (1).

Error in bmGui>plotMeCallback (line 693)
    if plottingWindowLims(2)>nSamplesInRecording-1

Error in bmGui (line 457)
plotMeCallback({},{},S,0);

Error in resp (line 17)
cleanedBmObj=bmGui(bmObj);
```

**Comment by marcpabst** [comment]
I identified the problem as relying on the existence of the `inhalePauseOnsets` and  `exhalePauseOnsets` fields. When using `humanBB`, those fields are empty which causes the concatenated array to be shorter than expected thus leading to the out of bounds exception I was presented with. 

For now, I made a rather small modification (https://github.com/zelanolab/breathmetrics/compare/master...marcpabst:master) which should enable us to use the gui for our data.

**Comment by torbenator** [comment]
So sorry about that. I totally forgot to test for breathing belt. I took a look at your code and I like your fix. I'll make sure everything with airflow recordings still works with this change and merge it with master. Thank you!

**Comment by marcpabst** [comment]
There actually two more problems:
- the **offset** value in the left panel (in the gui) is the offset of each exhale, which makes sense but is obviously not available for `humanBB` data
- the way you estimate exhale & inhale onsets for `humanBB` data doesn't guarantee that the first inhale _is before_ the first exhale. Contrary to that, the gui function assumes that and can't handle data where the breaths are 'the wrong way around'.

If you like, I can make a PR regarding those problems.

**Comment by torbenator** [comment]
Wow! Great catch. I had no idea it did that. 
I really haven't used this for much breathing belt data and I appologise for making it so difficult to use. I'm working on this now. Hopefully I can have this done soon. Thanks so much for the feedback.

**Comment by torbenator** [comment]
OK. I fixed both of those issues. I tried it on my breathing belt data and didn't get any errors. Please let me know if you need anything else!

Thanks

**Comment by marcpabst** [comment]
Thanks a lot! I'll give it a go and report back as soon as I can!
